### ISSUE TITLE
no more 64-bit simulator detection

### ISSUE THREAD

**Issue by feasibletrash0** [appcelerator/ioslib#27]
After commit 78a75b, 64-bit simulator detection was removed for unspecified reasons. Before you could query if a simulator is 64 bit with simulator["64bit"], and now you cannot.

**Comment by cb1kenobi** [comment]
We used a tool called `ios-sim` that detected iOS Simulators using private frameworks. It was great. We could see if the simulators were 32 or 64-bit.

Then Xcode 7 was released. `ios-sim` blew up because those private frameworks changed. We tried to fix `ios-sim`, but we realized it was an upward battle and one that we didn't need to fight.

Starting with Xcode 6 (I think), there's a handy CLI tool called `simctl` that does pretty much everything `ios-sim` does. We have updated ioslib to use `simctl` and thus Xcode 7 works. Unfortunately we lost the ability to detect 64-bit simulators, but it's not a huge deal though because I believe all iOS Simulators are 64-bit now. From the iOS Simulator's Hardware > Devices menu, you cannot select a non-64-bit simulator nor can you add one via the iOS Simulator's "Manage Devices" window.
